//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CCDExamp.rc
//
#define IDS_STRING1                     1
#define IDOK2                           3
#define IDOK1                           4
#define IDCANCEL2                       5
#define IDDEFAULT                       6
#define NOBIOSERR                       101
#define NOCCDERR                        102
#define IDD_DIALOG1                     104
#define IDD_EXPTIME                     104
#define IDD_DIALOG2                     105
#define IDD_SETTEMP                     106
#define IDD_SETEC                       107
#define IDD_SETUPAD                     108
#define IDD_ALLOCBBUF                   110
#define IDD_CHOOSEBOARD                 111
#define IDD_SETROI_3                    112
#define IDD_SETROI_5                    113
#define IDD_FULLBIN                     114
#define IDD_SETGAMMA                    116
#define IDD_SETAREA                     117
#define IDD_SETFULLBIN                  118
#define IDD_SETDAC                      119
#define IDC_ADAMP                       1002
#define IDC_M_EXPTIME                   1003
#define IDC_TLevel                      1004
#define IDC_M_REPTIME                   1004
#define IDC_SDAT                        1005
#define IDC_ExtTrig                     1006
#define IDC_BDAT                        1006
#define IDC_ADOFS                       1007
#define IDC_SEC                         1007
#define IDC_ADAMP2                      1008
#define IDC_BEC                         1008
#define IDC_TIGAIN                      1009
#define IDC_ADSHA                       1010
#define IDC_ECCNT_RADIO1                1013
#define IDC_ECCNT_RADIO2                1014
#define IDC_ECCNT_RADIO3                1015
#define IDC_ECCNT_RADIO4                1016
#define IDC_RADIO1                      1017
#define IDC_RADIO2                      1018
#define IDC_RADIO3                      1019
#define IDC_RADIO1_B                    1020
#define IDC_nob                         1021
#define IDC_RADIO2_B                    1021
#define IDC_nos                         1022
#define IDC_nospb                       1022
#define IDC_RADIO6                      1022
#define IDC_RADIO3_B                    1022
#define IDALLOC                         1023
#define IDC_BUILTINRAM                  1024
#define IDC_FREERAM                     1025
#define IDC_CALCRAM                     1026
#define IDC_EC_RADIO_BOTH               1026
#define IDC_ALLOCRAM                    1027
#define IDC_ROI_1                       1027
#define IDALLOC2                        1028
#define IDCALC                          1028
#define IDC_ROI_2                       1028
#define IDC_ROI_3                       1029
#define IDC_ROI_4                       1030
#define REP_ERR_MESS                    1030
#define IDC_ROI_5                       1031
#define IDC_GAMMA_WHITE                 1031
#define IDC_ROI_6                       1032
#define IDC_GAMMA_BLACK                 1032
#define IDC_COMBO_STI                   1033
#define IDC_COMBO_BTI                   1034
#define IDC_COMBO1                      1035
#define IDC_DAC_0                       1035
#define IDC_COMBO_TOR                   1036
#define IDC_DAC_1                       1036
#define IDC_DAC_2                       1037
#define IDC_DAC_3                       1038
#define IDC_DAC_4                       1039
#define IDC_DAC_5                       1040
#define IDC_DAC_6                       1041
#define IDC_DAC_7                       1042
#define IDC_EC_RADIO2                   1060
#define IDC_EC_RADIO3                   1061
#define IDC_EC_RADIO5                   1062
#define IDC_EC_RADIO4                   1063
#define IDC_EC_RADIO6                   1064
#define IDC_EC_RADIO8                   1065
#define IDC_EC_RADIO9                   1066
#define IDC_EC_RADIO18                  1067
#define IDC_EC_RADIO19                  1068
#define IDC_EC_RADIO17                  1069
#define IDC_EC_RADIO20                  1070
#define IDC_CHECK_NOPDARS               1158
#define IDC_SETDAT                      1159
#define IDC_SETXDLY                     1165
#define IDC_SETTCNT                     1166
#define IDC_SETTCNT2                    1167
#define IDC_EC_RADIO1                   1168
#define IDC_EC_RADIO7                   1169
#define IDC_SETECADJ                    1172
#define IDC_RADIO11                     1177
#define IDC_RADIO12                     1178
#define IDC_RADIO13                     1179
#define IDC_RADIO14                     1180
#define IDM_START                       40000
#define IDM_ABOUT                       40001
#define IDM_SETEXP                      40006
#define IDM_START_FF                    40007
#define IDM_ABOUTTIME                   40008
#define IDM_SETTLEVEL                   40009
#define IDM_ABOUTKEYS                   40010
#define IDM_ShowTRMS                    40011
#define ID_HELP_SPACE0                  40012
#define IDM_ABOUTS0                     40013
#define IDM_SETEC                       40014
#define ID_START_SETUPAD                40015
#define IDM_SetupCDS_AD                 40016
#define ID_HELP_PCISPACE                40017
#define IDM_ABOUTPCI                    40018
#define IDM_ABOUTDMA                    40019
#define IDM_ABOUTCFS                    40020
#define ID_TRACKBAR                     40021
#define ID_START_ALLOCATEBUFF           40021
#define ID_START_ALLOC                  40022
#define ID_START_CHOOSEBOARD            40023
#define ID_CHOOSEBOARD                  40024
#define ID_2DVIEW_SHOW                  40025
#define ID_2DVIEW_SETGAMMA              40027
#define ID_START_SETRANGEOFINTEREST     40028
#define ID_SETRANGEOFINTEREST_3RANGES   40029
#define ID_SETRANGEOFINTEREST_AREAMODE  40033
#define ID_AREAMODE                     40034
#define ID_HELP_DAC                     40035
#define IDM_ABOUTDAC                    40036
#define ID_START_SETDAC                 40037
#define ID_SETDAC                       40038
#define ID_SETRANGEOFINTEREST_5RANGES   40130
#define ID_SETFULLBINNING               40131
#define ROI_ERR_MESS                    40132
#define ID_START_STARTCONTINUOUSLY      40133
#define ranges                          40134
#define text3                           40135
#define text2                           40135
#define white_str                       40137
#define black_str                       40138
#define ranges1                         40139
#define ranges2                         40140
#define ranges3                         40141
#define ranges4                         40142
#define ranges5                         40143
#define ranges6                         40144
#define ranges7                         40145
#define IDC_EDIT1                       -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40039
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
