/************************************************************************
*  File: lscpciej_lib.c
*
*  Library for accessing LSCPCIEJ devices using a Kernel PlugIn driver.
*  The code accesses hardware using WinDriver's WDC library.
*  Code was generated by DriverWizard v12.0.0.
*
*  Jungo Connectivity Confidential. Copyright (c) 2015 Jungo Connectivity Ltd.  http://www.jungo.com
*************************************************************************/

#if defined(__KERNEL__)
    #include "kpstdlib.h"
#else
    #include <stdio.h>
    #include <stdarg.h>
#endif
#include "wdc_defs.h"
#include "utils.h"
#include "status_strings.h"
#include "lscpciej_lib.h"

/*************************************************************
  Internal definitions
 *************************************************************/
/* WinDriver license registration string */
/* TODO: When using a registered WinDriver version, make sure the license
 *       string below is your specific WinDriver license registration string
 *       and set the driver name to your driver's name */
//#define LSCPCIEJ_DEFAULT_LICENSE_STRING "643c749b4b3f16a065cd01a30e8f3ea2d6ff4a01972d366c100fcf7a.WD1180_64_NL_Entwicklungsburo_Stresing"
#define LSCPCIEJ_DEFAULT_DRIVER_NAME WD_DEFAULT_DRIVER_NAME_BASE

/* LSCPCIEJ device information struct */
typedef struct {
    LSCPCIEJ_INT_HANDLER   funcDiagIntHandler;
    LSCPCIEJ_EVENT_HANDLER funcDiagEventHandler;
} LSCPCIEJ_DEV_CTX, *PLSCPCIEJ_DEV_CTX;
/* TODO: You can add fields to store additional device-specific information */

static CHAR gsLSCPCIEJ_LastErr[256];

static DWORD LibInit_count = 0;
/*************************************************************
  Static functions prototypes and inline implementation
 *************************************************************/
#if !defined(__KERNEL__)
static BOOL DeviceValidate(const PWDC_DEVICE pDev);
static void DLLCALLCONV LSCPCIEJ_IntHandler(PVOID pData);
static void LSCPCIEJ_EventHandler(WD_EVENT *pEvent, PVOID pData);
#endif
static void ErrLog(const CHAR *sFormat, ...);
static void TraceLog(const CHAR *sFormat, ...);

static inline BOOL IsValidDevice(PWDC_DEVICE pDev, const CHAR *sFunc)
{
    if (!pDev || !WDC_GetDevContext(pDev))
    {
        snprintf(gsLSCPCIEJ_LastErr, sizeof(gsLSCPCIEJ_LastErr) - 1, "%s: NULL device %s\n",
            sFunc, !pDev ? "handle" : "context");
        ErrLog(gsLSCPCIEJ_LastErr);
        return FALSE;
    }

    return TRUE;
}

/*************************************************************
  Functions implementation
 *************************************************************/
/* -----------------------------------------------
    LSCPCIEJ and WDC library initialize/uninit
   ----------------------------------------------- */
DWORD LSCPCIEJ_LibInit(void)
{
    DWORD dwStatus;

    /* init only once */
    if (++LibInit_count > 1)
        return WD_STATUS_SUCCESS;

#if defined(WD_DRIVER_NAME_CHANGE)
    /* Set the driver name */
    if (!WD_DriverName(LSCPCIEJ_DEFAULT_DRIVER_NAME))
    {
        ErrLog("Failed to set the driver name for WDC library.\n");
        return WD_SYSTEM_INTERNAL_ERROR;
    }
#endif

    /* Set WDC library's debug options (default: level TRACE, output to Debug Monitor) */
    dwStatus = WDC_SetDebugOptions(WDC_DBG_DEFAULT, NULL);
    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed to initialize debug options for WDC library.\n"
            "Error 0x%lx - %s\n", dwStatus, Stat2Str(dwStatus));

        return dwStatus;
    }

    /* Open a handle to the driver and initialize the WDC library */
    dwStatus = WDC_DriverOpen(WDC_DRV_OPEN_DEFAULT, LSCPCIEJ_DEFAULT_LICENSE_STRING);
    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed to initialize the WDC library. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));

        return dwStatus;
    }

    return WD_STATUS_SUCCESS;
}

DWORD LSCPCIEJ_LibUninit(void)
{
    DWORD dwStatus;

    if (--LibInit_count > 0)
        return WD_STATUS_SUCCESS;

    /* Uninit the WDC library and close the handle to WinDriver */
    dwStatus = WDC_DriverClose();
    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed to uninit the WDC library. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));
    }

    return dwStatus;
}

#if !defined(__KERNEL__)
/* -----------------------------------------------
    Device open/close
   ----------------------------------------------- */
WDC_DEVICE_HANDLE LSCPCIEJ_DeviceOpen(const WD_PCI_CARD_INFO *pDeviceInfo)
{
    DWORD dwStatus;
    PLSCPCIEJ_DEV_CTX pDevCtx = NULL;
    WDC_DEVICE_HANDLE hDev = NULL;
    LSCPCIEJ_DEV_ADDR_DESC devAddrDesc;
    PWDC_DEVICE pDev;

    /* Validate arguments */
    if (!pDeviceInfo)
    {
        ErrLog("LSCPCIEJ_DeviceOpen: Error - NULL device information struct pointer\n");
        return NULL;
    }

    /* Allocate memory for the LSCPCIEJ device context */
    pDevCtx = (PLSCPCIEJ_DEV_CTX)malloc(sizeof(LSCPCIEJ_DEV_CTX));
    if (!pDevCtx)
    {
        ErrLog("Failed allocating memory for LSCPCIEJ device context\n");
        return NULL;
    }

    BZERO(*pDevCtx);

    /* Open a WDC device handle */
    dwStatus = WDC_PciDeviceOpen(&hDev, pDeviceInfo, pDevCtx, NULL, NULL, NULL);
    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed opening a WDC device handle. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));
        goto Error;
    }

	

    pDev = hDev;
    devAddrDesc.dwNumAddrSpaces = pDev->dwNumAddrSpaces;
    devAddrDesc.pAddrDesc = pDev->pAddrDesc;

    /* Open a handle to a Kernel PlugIn driver */
	dwStatus = WDC_KernelPlugInOpen(hDev, KP_LSCPCIEJ_DRIVER_NAME, &devAddrDesc);
	if (WD_STATUS_SUCCESS != dwStatus)
	{
		ErrLog("Failed opening a Kernel Plugin WDC device handle. Error 0x%lx - %s\n",
			dwStatus, Stat2Str(dwStatus));
		goto Error;
	}
	WDC_Err("succesfull created KErnelplugin handle\n");


    /* Validate device information */
    if (!DeviceValidate((PWDC_DEVICE)hDev))
        goto Error;

    /* Return handle to the new device */
    TraceLog("LSCPCIEJ_DeviceOpen: Opened a LSCPCIEJ device (handle 0x%p)\n"
        "Device uses a Kernel PlugIn driver (%s)\n", hDev, KP_LSCPCIEJ_DRIVER_NAME);
    return hDev;

Error:
    if (hDev)
        LSCPCIEJ_DeviceClose(hDev);
    else
        free(pDevCtx);

    return NULL;
}

BOOL LSCPCIEJ_DeviceClose(WDC_DEVICE_HANDLE hDev)
{
    DWORD dwStatus;
    PWDC_DEVICE pDev = (PWDC_DEVICE)hDev;
    PLSCPCIEJ_DEV_CTX pDevCtx;

    TraceLog("LSCPCIEJ_DeviceClose entered. Device handle: 0x%p\n", hDev);

    if (!hDev)
    {
        ErrLog("LSCPCIEJ_DeviceClose: Error - NULL device handle\n");
        return FALSE;
    }

    pDevCtx = (PLSCPCIEJ_DEV_CTX)WDC_GetDevContext(pDev);

    /* Disable interrupts */
    if (WDC_IntIsEnabled(hDev))
    {
        dwStatus = LSCPCIEJ_IntDisable(hDev);
        if (WD_STATUS_SUCCESS != dwStatus)
        {
            ErrLog("Failed disabling interrupts. Error 0x%lx - %s\n",
                dwStatus, Stat2Str(dwStatus));
        }
    }

    /* Close the device */
    dwStatus = WDC_PciDeviceClose(hDev);
    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed closing a WDC device handle (0x%p). Error 0x%lx - %s\n",
            hDev, dwStatus, Stat2Str(dwStatus));
    }

    /* Free LSCPCIEJ device context memory */
    if (pDevCtx)
        free(pDevCtx);

    return (WD_STATUS_SUCCESS == dwStatus);
}

static BOOL DeviceValidate(const PWDC_DEVICE pDev)
{
    DWORD i, dwNumAddrSpaces = pDev->dwNumAddrSpaces;

    /* TODO: You can modify the implementation of this function in order to
             verify that the device has all expected resources. */

    /* Verify that the device has at least one active address space */
    for (i = 0; i < dwNumAddrSpaces; i++)
    {
        if (WDC_AddrSpaceIsActive(pDev, i))
            return TRUE;
    }

    /* In this sample we accept the device even if it doesn't have any
     * address spaces */
    TraceLog("Device does not have any active memory or I/O address spaces\n");
    return TRUE;
}

/* -----------------------------------------------
    Interrupts
   ----------------------------------------------- */
static void DLLCALLCONV LSCPCIEJ_IntHandler(PVOID pData)
{
    PWDC_DEVICE pDev = (PWDC_DEVICE)pData;
    PLSCPCIEJ_DEV_CTX pDevCtx = (PLSCPCIEJ_DEV_CTX)WDC_GetDevContext(pDev);
    LSCPCIEJ_INT_RESULT intResult;

    BZERO(intResult);
    intResult.dwCounter = pDev->Int.dwCounter;
    intResult.dwLost = pDev->Int.dwLost;
    intResult.waitResult = (WD_INTERRUPT_WAIT_RESULT)pDev->Int.fStopped;
    intResult.dwEnabledIntType = WDC_GET_ENABLED_INT_TYPE(pDev);
    intResult.dwLastMessage = WDC_GET_ENABLED_INT_LAST_MSG(pDev);

    /* Execute the diagnostics application's interrupt handler routine */
    pDevCtx->funcDiagIntHandler((WDC_DEVICE_HANDLE)pDev, &intResult);
}

static BOOL IsItemExists(PWDC_DEVICE pDev, ITEM_TYPE item)
{
    DWORD i, dwNumItems = pDev->cardReg.Card.dwItems;

    for (i = 0; i < dwNumItems; i++)
    {
        if ((ITEM_TYPE)(pDev->cardReg.Card.Item[i].item) == item)
            return TRUE;
    }

    return FALSE;
}

DWORD LSCPCIEJ_IntEnable(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_INT_HANDLER funcIntHandler)
{
    DWORD dwStatus;
    PWDC_DEVICE pDev = (PWDC_DEVICE)hDev;
    PLSCPCIEJ_DEV_CTX pDevCtx;

    TraceLog("LSCPCIEJ_IntEnable entered. Device handle: 0x%p\n", hDev);

    if (!IsValidDevice(pDev, "LSCPCIEJ_IntEnable"))
        return WD_INVALID_PARAMETER;

    if (!IsItemExists(pDev, ITEM_INTERRUPT))
        return WD_OPERATION_FAILED;

    pDevCtx = (PLSCPCIEJ_DEV_CTX)WDC_GetDevContext(pDev);

    /* Check if interrupts are already enabled */
    if (WDC_IntIsEnabled(hDev))
    {
        ErrLog("Interrupts are already enabled ...\n");
        return WD_OPERATION_ALREADY_DONE;
    }

    /* Store the diag interrupt handler routine, which will be executed by
       LSCPCIEJ_IntHandler() when an interrupt is received */
    pDevCtx->funcDiagIntHandler = funcIntHandler;

    /* Enable the interrupts */
    /* NOTE: When adding read transfer commands, set the INTERRUPT_CMD_COPY flag
             in the 4th argument (dwOptions) passed to WDC_IntEnable() */
    dwStatus = WDC_IntEnable(hDev, NULL, 0, 0,
        LSCPCIEJ_IntHandler, (PVOID)pDev, WDC_IS_KP(hDev));
	WDC_Err("Is the Kernel active: %u \n", WDC_IS_KP(hDev));

    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed enabling interrupts. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));

        return dwStatus;
    }

    /* TODO: You can add code here to write to the device in order
             to physically enable the hardware interrupts */

    TraceLog("LSCPCIEJ_IntEnable: Interrupts enabled\n");

    return WD_STATUS_SUCCESS;
}

DWORD LSCPCIEJ_IntDisable(WDC_DEVICE_HANDLE hDev)
{
    DWORD dwStatus;
    PWDC_DEVICE pDev = (PWDC_DEVICE)hDev;
    PLSCPCIEJ_DEV_CTX pDevCtx;

    TraceLog("LSCPCIEJ_IntDisable entered. Device handle: 0x%p\n", hDev);

    if (!IsValidDevice(pDev, "LSCPCIEJ_IntDisable"))
        return WD_INVALID_PARAMETER;

    pDevCtx = (PLSCPCIEJ_DEV_CTX)WDC_GetDevContext(pDev);

    if (!WDC_IntIsEnabled(hDev))
    {
        ErrLog("Interrupts are already disabled ...\n");
        return WD_OPERATION_ALREADY_DONE;
    }

    /* TODO: You can add code here to write to the device in order
             to physically disable the hardware interrupts */

    /* Disable the interrupts */
    dwStatus = WDC_IntDisable(hDev);
    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed disabling interrupts. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));
    }

    return dwStatus;
}

BOOL LSCPCIEJ_IntIsEnabled(WDC_DEVICE_HANDLE hDev)
{
    if (!IsValidDevice((PWDC_DEVICE)hDev, "LSCPCIEJ_IntIsEnabled"))
        return FALSE;

    return WDC_IntIsEnabled(hDev);
}

/* -----------------------------------------------
    Plug-and-play and power management events
   ----------------------------------------------- */
static void LSCPCIEJ_EventHandler(WD_EVENT *pEvent, PVOID pData)
{
    PWDC_DEVICE pDev = (PWDC_DEVICE)pData;
    PLSCPCIEJ_DEV_CTX pDevCtx = (PLSCPCIEJ_DEV_CTX)WDC_GetDevContext(pDev);

    TraceLog("LSCPCIEJ_EventHandler entered, pData: 0x%p, dwAction 0x%lx\n",
        pData, pEvent->dwAction);

    /* Execute the diagnostics application's event handler function */
    pDevCtx->funcDiagEventHandler((WDC_DEVICE_HANDLE)pDev, pEvent->dwAction);
}

DWORD LSCPCIEJ_EventRegister(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_EVENT_HANDLER funcEventHandler)
{
    DWORD dwStatus;
    PWDC_DEVICE pDev = (PWDC_DEVICE)hDev;
    PLSCPCIEJ_DEV_CTX pDevCtx;
    DWORD dwActions = WD_ACTIONS_ALL;
    /* TODO: Modify the above to set up the plug-and-play/power management
             events for which you wish to receive notifications.
             dwActions can be set to any combination of the WD_EVENT_ACTION
             flags defined in windrvr.h */

    TraceLog("LSCPCIEJ_EventRegister entered. Device handle: 0x%p\n", hDev);

    if (!IsValidDevice(pDev, "LSCPCIEJ_EventRegister"))
        return WD_INVALID_PARAMETER;

    pDevCtx = (PLSCPCIEJ_DEV_CTX)WDC_GetDevContext(pDev);

    /* Check if event is already registered */
    if (WDC_EventIsRegistered(hDev))
    {
        ErrLog("Events are already registered ...\n");
        return WD_OPERATION_ALREADY_DONE;
    }

    /* Store the diag event handler routine to be executed from LSCPCIEJ_EventHandler() upon an event */
    pDevCtx->funcDiagEventHandler = funcEventHandler;

    /* Register event */
    dwStatus = WDC_EventRegister(hDev, dwActions, LSCPCIEJ_EventHandler, hDev, TRUE);

    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed to register events. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));
        return dwStatus;
    }

    TraceLog("Events registered\n");

    return WD_STATUS_SUCCESS;
}

DWORD LSCPCIEJ_EventUnregister(WDC_DEVICE_HANDLE hDev)
{
    DWORD dwStatus;

    TraceLog("LSCPCIEJ_EventUnregister entered. Device handle: 0x%p\n", hDev);

    if (!IsValidDevice((PWDC_DEVICE)hDev, "LSCPCIEJ_EventUnregister"))
        return WD_INVALID_PARAMETER;

    if (!WDC_EventIsRegistered(hDev))
    {
        ErrLog("Cannot unregister events - no events currently registered ...\n");
        return WD_OPERATION_ALREADY_DONE;
    }

    dwStatus = WDC_EventUnregister(hDev);

    if (WD_STATUS_SUCCESS != dwStatus)
    {
        ErrLog("Failed to unregister events. Error 0x%lx - %s\n",
            dwStatus, Stat2Str(dwStatus));
    }

    return dwStatus;
}

BOOL LSCPCIEJ_EventIsRegistered(WDC_DEVICE_HANDLE hDev)
{
    if (!IsValidDevice((PWDC_DEVICE)hDev, "LSCPCIEJ_EventIsRegistered"))
        return FALSE;

    return WDC_EventIsRegistered(hDev);
}
#endif

/* -----------------------------------------------
    Address spaces information
   ----------------------------------------------- */
DWORD LSCPCIEJ_GetNumAddrSpaces(WDC_DEVICE_HANDLE hDev)
{
    PWDC_DEVICE pDev = (PWDC_DEVICE)hDev;

    if (!IsValidDevice(pDev, "LSCPCIEJ_GetNumAddrSpaces"))
        return 0;

    return pDev->dwNumAddrSpaces;
}

BOOL LSCPCIEJ_GetAddrSpaceInfo(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_ADDR_SPACE_INFO *pAddrSpaceInfo)
{
    PWDC_DEVICE pDev = (PWDC_DEVICE)hDev;
    WDC_ADDR_DESC *pAddrDesc;
    DWORD dwAddrSpace, dwMaxAddrSpace;
    BOOL fIsMemory;

    if (!IsValidDevice(pDev, "LSCPCIEJ_GetAddrSpaceInfo"))
        return FALSE;

#if defined(DEBUG)
    if (!pAddrSpaceInfo)
    {
        ErrLog("LSCPCIEJ_GetAddrSpaceInfo: Error - NULL address space information pointer\n");
        return FALSE;
    }
#endif

    dwAddrSpace = pAddrSpaceInfo->dwAddrSpace;
    dwMaxAddrSpace = pDev->dwNumAddrSpaces - 1;

    if (dwAddrSpace > dwMaxAddrSpace)
    {
        ErrLog("LSCPCIEJ_GetAddrSpaceInfo: Error - Address space %ld is out of range (0 - %ld)\n",
            dwAddrSpace, dwMaxAddrSpace);
        return FALSE;
    }

    pAddrDesc = &pDev->pAddrDesc[dwAddrSpace];

    fIsMemory = WDC_ADDR_IS_MEM(pAddrDesc);

    snprintf(pAddrSpaceInfo->sName, MAX_NAME - 1, "BAR %ld", dwAddrSpace);
    snprintf(pAddrSpaceInfo->sType, MAX_TYPE - 1, fIsMemory ? "Memory" : "I/O");

    if (WDC_AddrSpaceIsActive(pDev, dwAddrSpace))
    {
        WD_ITEMS *pItem = &pDev->cardReg.Card.Item[pAddrDesc->dwItemIndex];
        PHYS_ADDR pAddr = fIsMemory ? pItem->I.Mem.pPhysicalAddr : pItem->I.IO.pAddr;

        snprintf(pAddrSpaceInfo->sDesc, MAX_DESC - 1, "0x%0*I64X - 0x%0*I64X (0x%I64x bytes)",
            (int)WDC_SIZE_64 * 2, pAddr,
            (int)WDC_SIZE_64 * 2, pAddr + pAddrDesc->qwBytes - 1,
            pAddrDesc->qwBytes);
    }
    else
        snprintf(pAddrSpaceInfo->sDesc, MAX_DESC - 1, "Inactive address space");

    /* TODO: You can modify the code above to set a different address space name/description */

    return TRUE;
}

// Function: LSCPCIEJ_Read´EBST´()
//   Read from ´EBST´ register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read´EBST´ (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_´EBST´_SPACE, LSCPCIEJ_´EBST´_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadVCLKCTRL()
//   Read from VCLKCTRL register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadVCLKCTRL (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_VCLKCTRL_SPACE, LSCPCIEJ_VCLKCTRL_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadFIFOCNT()
//   Read from FIFOCNT register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadFIFOCNT (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_FIFOCNT_SPACE, LSCPCIEJ_FIFOCNT_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadPIXREG()
//   Read from PIXREG register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadPIXREG (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_PIXREG_SPACE, LSCPCIEJ_PIXREG_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadXCKCNTLL()
//   Read from XCKCNTLL register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadXCKCNTLL (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_XCKCNTLL_SPACE, LSCPCIEJ_XCKCNTLL_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadCTRLA()
//   Read from CTRLA register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadCTRLA (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_CTRLA_SPACE, LSCPCIEJ_CTRLA_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadDBR()
//   Read from DBR register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadDBR (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_DBR_SPACE, LSCPCIEJ_DBR_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadXCKLL()
//   Read from XCKLL register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadXCKLL (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_XCKLL_SPACE, LSCPCIEJ_XCKLL_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadDAT()
//   Read from DAT register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadDAT (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_DAT_SPACE, LSCPCIEJ_DAT_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadEC()
//   Read from EC register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadEC (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_EC_SPACE, LSCPCIEJ_EC_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_WriteEC()
//   Write to EC register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
//   data [in] the data to write to the register.
// Return Value:
//   None.
void LSCPCIEJ_WriteEC (WDC_DEVICE_HANDLE hDev, UINT32 data)
{
    WDC_WriteAddr32(hDev, LSCPCIEJ_EC_SPACE, LSCPCIEJ_EC_OFFSET, data);
}

// Function: LSCPCIEJ_ReadTOR()
//   Read from TOR register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadTOR (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_TOR_SPACE, LSCPCIEJ_TOR_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadARREG()
//   Read from ARREG register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadARREG (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_ARREG_SPACE, LSCPCIEJ_ARREG_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadGIOREG()
//   Read from GIOREG register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadGIOREG (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_GIOREG_SPACE, LSCPCIEJ_GIOREG_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadDELAY EC/REG()
//   Read from DELAY EC/REG register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadDELAY_ECREG (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_DELAY_ECREG_SPACE, LSCPCIEJ_DELAY_ECREG_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadIRQREAD()
//   Read from IRQREAD register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadIRQREAD (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_IRQREAD_SPACE, LSCPCIEJ_IRQREAD_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_ReadPCI board version()
//   Read from PCI board version register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_ReadPCI_board_version (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_PCI_board_version_SPACE, LSCPCIEJ_PCI_board_version_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_Read2()
//   Read from 2 register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read2 (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_2_SPACE, LSCPCIEJ_2_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_Read1()
//   Read from 1 register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read1 (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_1_SPACE, LSCPCIEJ_1_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_Read3()
//   Read from 3 register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read3 (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_3_SPACE, LSCPCIEJ_3_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_Read0x8()
//   Read from 0x8 register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read0x8 (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_0x8_SPACE, LSCPCIEJ_0x8_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_Read0x4()
//   Read from 0x4 register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read0x4 (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_0x4_SPACE, LSCPCIEJ_0x4_OFFSET, &data);
    return data;
}

// Function: LSCPCIEJ_Read0x0()
//   Read from 0x0 register.
// Parameters:
//   hDev [in] handle to the card as received from LSCPCIEJ_DeviceOpen().
// Return Value:
//   The value read from the register.
UINT32 LSCPCIEJ_Read0x0 (WDC_DEVICE_HANDLE hDev)
{
    UINT32 data;

    WDC_ReadAddr32(hDev, LSCPCIEJ_0x0_SPACE, LSCPCIEJ_0x0_OFFSET, &data);
    return data;
}

/* -----------------------------------------------
    Debugging and error handling
   ----------------------------------------------- */
static void ErrLog(const CHAR *sFormat, ...)
{
    va_list argp;
    va_start(argp, sFormat);
    vsnprintf(gsLSCPCIEJ_LastErr, sizeof(gsLSCPCIEJ_LastErr) - 1, sFormat, argp);
#if defined(DEBUG)
#if defined(__KERNEL__)
    WDC_Err("KP LSCPCIEJ lib: %s", LSCPCIEJ_GetLastErr());
#else
    WDC_Err("LSCPCIEJ lib: %s", LSCPCIEJ_GetLastErr());
#endif
#endif
    va_end(argp);
}

static void TraceLog(const CHAR *sFormat, ...)
{
#if defined(DEBUG)
    CHAR sMsg[256];
    va_list argp;
    va_start(argp, sFormat);
    vsnprintf(sMsg, sizeof(sMsg) - 1, sFormat, argp);
#if defined(__KERNEL__)
    WDC_Trace("KP LSCPCIEJ lib: %s", sMsg);
#else
    WDC_Trace("LSCPCIEJ lib: %s", sMsg);
#endif
    va_end(argp);
#endif
}

const char *LSCPCIEJ_GetLastErr(void)
{
    return gsLSCPCIEJ_LastErr;
}
