#ifndef _LSCPCIEJ_LIB_H_
#define _LSCPCIEJ_LIB_H_

/************************************************************************
*  File: lscpciej_lib.h
*
*  Library for accessing LSCPCIEJ devices using a Kernel PlugIn driver.
*  The code accesses hardware using WinDriver's WDC library.
*  Code was generated by DriverWizard v12.0.0.
*
*  Jungo Connectivity Confidential. Copyright (c) 2015 Jungo Connectivity Ltd.  http://www.jungo.com
*************************************************************************/

#include "wdc_lib.h"
#include "wdc_defs.h"
#include "pci_regs.h"
#include "bits.h"

#ifdef __cplusplus
extern "C" {
#endif

/*************************************************************
  General definitions
 *************************************************************/
/* Kernel PlugIn driver name (should be no more than 8 characters) */
#define KP_LSCPCIEJ_DRIVER_NAME "KP_PCI"

/* Kernel PlugIn messages - used in WDC_CallKerPlug() calls (user mode) / KP_LSCPCIEJ_Call() (kernel mode) */
enum {
	KP_LSCPCIEJ_MSG_VERSION = 1, /* Query the version of the Kernel PlugIn */
	KP_LSCPCIEJ_MSG_HDMA = 2, /* Kernel Plugin receiving the DMA handle */
	KP_LSCPCIEJ_MSG_DWOPT = 3, /* Kernel Plugin receiving the DMA Options */
	KP_LSCPCIEJ_MSG_BUFSIZE = 4,
	KP_LSCPCIEJ_MSG_WDDMA = 5,
	KP_LSCPCIEJ_MSG_HDEV = 6
};

/* Kernel PlugIn messages status */
enum {
    KP_LSCPCIEJ_STATUS_OK = 0x1,
    KP_LSCPCIEJ_STATUS_MSG_NO_IMPL = 0x1000,
};

/* Default vendor and device IDs */
#define LSCPCIEJ_DEFAULT_VENDOR_ID 0x10EE /* Vendor ID */
#define LSCPCIEJ_DEFAULT_DEVICE_ID 0x7 /* Device ID */


/* Kernel PlugIn version information struct */
typedef struct {
    DWORD dwVer;
    CHAR cVer[100];
} KP_LSCPCIEJ_VERSION;

/* Device address description struct */
typedef struct {
    DWORD dwNumAddrSpaces;    /* Total number of device address spaces */
    WDC_ADDR_DESC *pAddrDesc; /* Array of device address spaces information */
} LSCPCIEJ_DEV_ADDR_DESC;

/* Address space information struct */
#define MAX_TYPE 8
typedef struct {
    DWORD dwAddrSpace;
    CHAR sType[MAX_TYPE];
    CHAR sName[MAX_NAME];
    CHAR sDesc[MAX_DESC];
} LSCPCIEJ_ADDR_SPACE_INFO;

/* Interrupt result information struct */
typedef struct
{
    DWORD dwCounter; /* Number of interrupts received */
    DWORD dwLost;    /* Number of interrupts not yet handled */
    WD_INTERRUPT_WAIT_RESULT waitResult; /* See WD_INTERRUPT_WAIT_RESULT values in windrvr.h */
    DWORD dwEnabledIntType; /* Interrupt type that was actually enabled
                               (MSI/MSI-X/Level Sensitive/Edge-Triggered) */
    DWORD dwLastMessage; /* Message data of the last received MSI/MSI-X
                            (Windows Vista and higher); N/A to line-based
                            interrupts) */
} LSCPCIEJ_INT_RESULT;
/* TODO: You can add fields to LSCPCIEJ_INT_RESULT to store any additional
         information that you wish to pass to your diagnostics interrupt
         handler routine (DiagIntHandler() in lscpciej_diag.c) */

/* LSCPCIEJ diagnostics interrupt handler function type */
typedef void (* LSCPCIEJ_INT_HANDLER)(WDC_DEVICE_HANDLE hDev,
    LSCPCIEJ_INT_RESULT *pIntResult);

/* LSCPCIEJ diagnostics plug-and-play and power management events handler function type */
typedef void (* LSCPCIEJ_EVENT_HANDLER)(WDC_DEVICE_HANDLE hDev,
	DWORD dwAction);

// LSCPCIEJ register definitions
enum { LSCPCIEJ_´EBST´_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_´EBST´_OFFSET = 0x9c };
enum { LSCPCIEJ_VCLKCTRL_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_VCLKCTRL_OFFSET = 0x98 };
enum { LSCPCIEJ_FIFOCNT_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_FIFOCNT_OFFSET = 0x94 };
enum { LSCPCIEJ_PIXREG_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_PIXREG_OFFSET = 0x90 };
enum { LSCPCIEJ_XCKCNTLL_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_XCKCNTLL_OFFSET = 0x8c };
enum { LSCPCIEJ_CTRLA_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_CTRLA_OFFSET = 0x84 };
enum { LSCPCIEJ_DBR_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_DBR_OFFSET = 0x80 };
enum { LSCPCIEJ_XCKLL_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_XCKLL_OFFSET = 0x88 };
enum { LSCPCIEJ_DAT_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_DAT_OFFSET = 0xa0 };
enum { LSCPCIEJ_EC_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_EC_OFFSET = 0xa4 };
enum { LSCPCIEJ_TOR_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_TOR_OFFSET = 0xa8 };
enum { LSCPCIEJ_ARREG_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_ARREG_OFFSET = 0xac };
enum { LSCPCIEJ_GIOREG_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_GIOREG_OFFSET = 0xb0 };
enum { LSCPCIEJ_DELAY_ECREG_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_DELAY_ECREG_OFFSET = 0xb4 };
enum { LSCPCIEJ_IRQREAD_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_IRQREAD_OFFSET = 0xb8 };
enum { LSCPCIEJ_PCI_board_version_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_PCI_board_version_OFFSET = 0xbc };
enum { LSCPCIEJ_2_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_2_OFFSET = 0x4 };
enum { LSCPCIEJ_1_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_1_OFFSET = 0x0 };
enum { LSCPCIEJ_3_SPACE = AD_PCI_BAR0 };
enum { LSCPCIEJ_3_OFFSET = 0x8 };
enum { LSCPCIEJ_0x8_SPACE = AD_PCI_BAR2 };
enum { LSCPCIEJ_0x8_OFFSET = 0x8 };
enum { LSCPCIEJ_0x4_SPACE = AD_PCI_BAR2 };
enum { LSCPCIEJ_0x4_OFFSET = 0x4 };
enum { LSCPCIEJ_0x0_SPACE = AD_PCI_BAR2 };
enum { LSCPCIEJ_0x0_OFFSET = 0x0 };

/*************************************************************
  Function prototypes
 *************************************************************/
DWORD LSCPCIEJ_LibInit(void);
DWORD LSCPCIEJ_LibUninit(void);

#if !defined(__KERNEL__)
WDC_DEVICE_HANDLE LSCPCIEJ_DeviceOpen(const WD_PCI_CARD_INFO *pDeviceInfo);
BOOL LSCPCIEJ_DeviceClose(WDC_DEVICE_HANDLE hDev);

DWORD LSCPCIEJ_IntEnable(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_INT_HANDLER funcIntHandler);
DWORD LSCPCIEJ_IntDisable(WDC_DEVICE_HANDLE hDev);
BOOL LSCPCIEJ_IntIsEnabled(WDC_DEVICE_HANDLE hDev);

DWORD LSCPCIEJ_EventRegister(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_EVENT_HANDLER funcEventHandler);
DWORD LSCPCIEJ_EventUnregister(WDC_DEVICE_HANDLE hDev);
BOOL LSCPCIEJ_EventIsRegistered(WDC_DEVICE_HANDLE hDev);
#endif

DWORD LSCPCIEJ_GetNumAddrSpaces(WDC_DEVICE_HANDLE hDev);
BOOL LSCPCIEJ_GetAddrSpaceInfo(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_ADDR_SPACE_INFO *pAddrSpaceInfo);

// Function: LSCPCIEJ_Read´EBST´()
//   Read from ´EBST´ register.
UINT32 LSCPCIEJ_Read´EBST´(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadVCLKCTRL()
//   Read from VCLKCTRL register.
UINT32 LSCPCIEJ_ReadVCLKCTRL(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadFIFOCNT()
//   Read from FIFOCNT register.
UINT32 LSCPCIEJ_ReadFIFOCNT(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadPIXREG()
//   Read from PIXREG register.
UINT32 LSCPCIEJ_ReadPIXREG(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadXCKCNTLL()
//   Read from XCKCNTLL register.
UINT32 LSCPCIEJ_ReadXCKCNTLL(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadCTRLA()
//   Read from CTRLA register.
UINT32 LSCPCIEJ_ReadCTRLA(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadDBR()
//   Read from DBR register.
UINT32 LSCPCIEJ_ReadDBR(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadXCKLL()
//   Read from XCKLL register.
UINT32 LSCPCIEJ_ReadXCKLL(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadDAT()
//   Read from DAT register.
UINT32 LSCPCIEJ_ReadDAT(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadEC()
//   Read from EC register.
UINT32 LSCPCIEJ_ReadEC(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_WriteEC()
//   Write to EC register.
void LSCPCIEJ_WriteEC(WDC_DEVICE_HANDLE hDev, UINT32 data);
// Function: LSCPCIEJ_ReadTOR()
//   Read from TOR register.
UINT32 LSCPCIEJ_ReadTOR(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadARREG()
//   Read from ARREG register.
UINT32 LSCPCIEJ_ReadARREG(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadGIOREG()
//   Read from GIOREG register.
UINT32 LSCPCIEJ_ReadGIOREG(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadDELAY EC/REG()
//   Read from DELAY EC/REG register.
UINT32 LSCPCIEJ_ReadDELAY_ECREG(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadIRQREAD()
//   Read from IRQREAD register.
UINT32 LSCPCIEJ_ReadIRQREAD(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_ReadPCI board version()
//   Read from PCI board version register.
UINT32 LSCPCIEJ_ReadPCI_board_version(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_Read2()
//   Read from 2 register.
UINT32 LSCPCIEJ_Read2(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_Read1()
//   Read from 1 register.
UINT32 LSCPCIEJ_Read1(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_Read3()
//   Read from 3 register.
UINT32 LSCPCIEJ_Read3(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_Read0x8()
//   Read from 0x8 register.
UINT32 LSCPCIEJ_Read0x8(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_Read0x4()
//   Read from 0x4 register.
UINT32 LSCPCIEJ_Read0x4(WDC_DEVICE_HANDLE hDev);
// Function: LSCPCIEJ_Read0x0()
//   Read from 0x0 register.
UINT32 LSCPCIEJ_Read0x0(WDC_DEVICE_HANDLE hDev);

const char *LSCPCIEJ_GetLastErr(void);

#ifdef __cplusplus
}
#endif

#endif