#ifndef DEFAULT_SETTINGS_H
#define DEFAULT_SETTINGS_H

#include "../shared_src/enum.h"

#define settingsUseSoftwarePollingDefault			false
#define settingNosDefault							1000
#define settingNobDefault							2
#define settingStiDefault							sti_STimer
#define settingBtiDefault							bti_BTimer
#define settingStime_in_microseconds_Default		1000
#define settingBtime_in_microseconds_Default		1000000
#define settingSdat_in_10nsDefault					0
#define settingBdat_in_10nsDefault					0
#define settingSslopeDefault						sslope_pos
#define settingBslopeDefault						bslope_pos
#define settingXckdelayIn10nsDefault				0
#define settingShutterSecIn10nsDefault				1
#define settingShutterBecIn10nsDefault				1
#define settingTriggerCcDefault						xck
#define settingBoardSelDefault						0
#define settingSensorTypeDefault					PDAsensor
#define settingCameraSystemDefault					camera_system_3001
#define settingCamcntDefault						1
#define settingPixelDefault							576
#define settingMshutDefault							false
#define settingLedDefault							false
#define settingSensorGainDefault					0
#define settingAdcGainDefault						0
#define settingCoolingDefault						0
#define settingDacDefault							false
#define settingShortrsDefault						false
#define settingGpxOffsetDefault						0
#define settingLinesDefault							64
#define settingVfreqDefault							7
#define settingFftModeDefault						full_binning
#define settingLinesBinningDefault					1
#define settingNumberOfRegionsDefault				3
#define settingKeepDefault							0xFF
#define settingRegionSizeEqualDefault				true
#define settingRegionSize1Default					10
#define settingRegionSize2Default					44
#define settingRegionSize3Default					10
#define settingRegionSize4Default					10
#define settingRegionSize5Default					10
#define settingRegionSize6Default					10
#define settingRegionSize7Default					10
#define settingRegionSize8Default					10
#define settingSensorOffsetChannel1Default			40000
#define settingSensorOffsetChannel2Default			40000
#define settingSensorOffsetChannel3Default			40000
#define settingSensorOffsetChannel4Default			40000
#define settingSensorOffsetChannel5Default			40000
#define settingSensorOffsetChannel6Default			40000
#define settingSensorOffsetChannel7Default			40000
#define settingSensorOffsetChannel8Default			40000
#define settingSensorOffsetBoard2Channel1Default	40000
#define settingSensorOffsetBoard2Channel2Default	40000
#define settingSensorOffsetBoard2Channel3Default	40000
#define settingSensorOffsetBoard2Channel4Default	40000
#define settingSensorOffsetBoard2Channel5Default	40000
#define settingSensorOffsetBoard2Channel6Default	40000
#define settingSensorOffsetBoard2Channel7Default	40000
#define settingSensorOffsetBoard2Channel8Default	40000
#define settingTorDefault							tor_xck
#define settingAdcModeDefault						normal
#define settingAdcCustomValueDefault				0
#define settingThemeDefault							lighttheme
#define settingSettingsLevelDefault					0
#define settingBecIn10nsDefault						0
#define settingShowCameraDefault					1
#define settingIsIrDefault							0
#define settingIOCtrlImpactStartPixelDefault		1078
#define settingIOCtrlOutput1WidthIn5nsDefault		50
#define settingIOCtrlOutput2WidthIn5nsDefault		50
#define settingIOCtrlOutput3WidthIn5nsDefault		50
#define settingIOCtrlOutput4WidthIn5nsDefault		50
#define settingIOCtrlOutput5WidthIn5nsDefault		50
#define settingIOCtrlOutput6WidthIn5nsDefault		50
#define settingIOCtrlOutput7WidthIn5nsDefault		50
#define settingIOCtrlOutput1DelayIn5nsDefault		0
#define settingIOCtrlOutput2DelayIn5nsDefault		100
#define settingIOCtrlOutput3DelayIn5nsDefault		200
#define settingIOCtrlOutput4DelayIn5nsDefault		300
#define settingIOCtrlOutput5DelayIn5nsDefault		400
#define settingIOCtrlOutput6DelayIn5nsDefault		500
#define settingIOCtrlOutput7DelayIn5nsDefault		600
#define settingIOCtrlT0PeriodIn10nsDefault			1000
#define settingContiniousPausInMicrosecondsDefault	1000
#define settingDmaBufferSizeInScansDefault			1000
#define settingTicntDefault							0
#define settingTocntDefault							0
#define settingUseEcDefault							0

#endif // DEFAULT_SETTINGS_H
