#include "globals.h"
#include "enum.h"
#include "default_settings.h"

uint32_t tmp_aPIXEL[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint32_t* aPIXEL = tmp_aPIXEL;
uint32_t tmp_aCAMCNT[MAXPCIECARDS] = { 1, 1, 1, 1, 1 };	// cameras parallel
uint32_t* aCAMCNT = tmp_aCAMCNT;	// cameras parallel
bool useSWTrig_temp = false;
bool* useSWTrig = &useSWTrig_temp;
uint16_t* temp_userBuffer[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBuffer= temp_userBuffer;
uint16_t* temp_userBufferWritePos[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBufferWritePos = temp_userBufferWritePos;
uint32_t BOARD_SEL = 1;
uint32_t numberOfInterrupts = 0;
uint8_t number_of_boards = 0;
uint32_t Nob = 1;
uint32_t tmp_Nosbp = 1000;
uint32_t* Nospb = &tmp_Nosbp;
bool abortMeasurementFlag = false;
bool continiousMeasurementFlag = false;
uint32_t continiousPause = 0;
struct global_settings settings_struct =
{
    .nos							= settingNosDefault,
    .nob							= settingNobDefault,
    .sti_mode						= settingStiDefault,
    .bti_mode						= settingBtiDefault,
    .stime_in_microsec				= settingStime_in_microseconds_Default,
    .btime_in_microsec				= settingBtime_in_microseconds_Default,
    .sdat_in_10ns					= settingSdat_in_10nsDefault,
    .bdat_in_10ns					= settingSdat_in_10nsDefault,
    .sslope							= settingSslopeDefault,
    .bslope							= settingBslopeDefault,
    .xckdelay_in_10ns				= settingXckdelayIn10nsDefault,
    .ShutterExpTimeIn10ns			= settingShutterExpTimeIn10nsDefault,
    .trigger_mode_cc				= settingTriggerCcDefault,
    .board_sel						= settingBoardSelDefault,
    .sensor_type					= settingSensorTypeDefault,
    .camera_system					= settingCameraSystemDefault,
    .camcnt							= settingCamcntDefault,
    .pixel							= settingPixelDefault,
    .mshut							= settingMshutDefault,
    .led_off						= settingLedDefault,
    .gain_switch					= settingGain3010Default,
    .gain_3030						= settingGain3030Default,
    .Temp_level						= settingCoolingDefault,
    .dac							= settingDacDefault,
    .enable_gpx						= settingGpxDefault,
    .gpx_offset						= settingGpxOffsetDefault,
    .FFTLines						= settingLinesDefault,
    .Vfreq							= settingVfreqDefault,
    .FFTMode						= settingFftModeDefault,
    .lines_binning					= settingLinesBinningDefault,
    .number_of_regions				= settingNumberOfRegionsDefault,
    .keep							= settingKeepDefault,
    .region_size[0]					= settingRegionSize1Default,
    .region_size[1]					= settingRegionSize2Default,
    .region_size[2]					= settingRegionSize3Default,
    .region_size[3]					= settingRegionSize4Default,
    .region_size[4]					= settingRegionSize5Default,
    .region_size[5]					= settingRegionSize6Default,
    .region_size[6]					= settingRegionSize7Default,
    .region_size[7]					= settingRegionSize8Default,
	.dac_output[0][0]				= settingSensorOffsetChannel1Default,
    .dac_output[0][1]				= settingSensorOffsetChannel2Default,
    .dac_output[0][2]				= settingSensorOffsetChannel3Default,
    .dac_output[0][3]				= settingSensorOffsetChannel4Default,
    .dac_output[0][4]				= settingSensorOffsetChannel5Default,
    .dac_output[0][5]				= settingSensorOffsetChannel6Default,
    .dac_output[0][6]				= settingSensorOffsetChannel7Default,
    .dac_output[0][7]				= settingSensorOffsetChannel8Default,
	.dac_output[1][0]				= settingSensorOffsetChannel1Default,
	.dac_output[1][1]				= settingSensorOffsetChannel2Default,
	.dac_output[1][2]				= settingSensorOffsetChannel3Default,
	.dac_output[1][3]				= settingSensorOffsetChannel4Default,
	.dac_output[1][4]				= settingSensorOffsetChannel5Default,
	.dac_output[1][5]				= settingSensorOffsetChannel6Default,
	.dac_output[1][6]				= settingSensorOffsetChannel7Default,
	.dac_output[1][7]				= settingSensorOffsetChannel8Default,
    .TORmodus						= settingTorDefault,
    .ADC_Mode						= settingAdcModeDefault,
    .ADC_custom_pattern				= settingAdcCustomValueDefault,
    .bec_in_10ns					= settingBecIn10nsDefault,
	.isIr							= settingIsIrDefault,
	.IOCtrl_impact_start_pixel		= settingIOCtrlImpactStartPixelDefault,
	.IOCtrl_output_width_in_5ns[0]	= settingIOCtrlOutput1WidthIn5nsDefault,
	.IOCtrl_output_width_in_5ns[1]	= settingIOCtrlOutput2WidthIn5nsDefault,
	.IOCtrl_output_width_in_5ns[2]	= settingIOCtrlOutput3WidthIn5nsDefault,
	.IOCtrl_output_width_in_5ns[3]	= settingIOCtrlOutput4WidthIn5nsDefault,
	.IOCtrl_output_width_in_5ns[4]	= settingIOCtrlOutput5WidthIn5nsDefault,
	.IOCtrl_output_width_in_5ns[5]	= settingIOCtrlOutput6WidthIn5nsDefault,
	.IOCtrl_output_width_in_5ns[6]	= settingIOCtrlOutput7WidthIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[0]	= settingIOCtrlOutput1DelayIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[1]	= settingIOCtrlOutput2DelayIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[2]	= settingIOCtrlOutput3DelayIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[3]	= settingIOCtrlOutput4DelayIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[4]	= settingIOCtrlOutput5DelayIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[5]	= settingIOCtrlOutput6DelayIn5nsDefault,
	.IOCtrl_output_delay_in_5ns[6]	= settingIOCtrlOutput7DelayIn5nsDefault,
	.IOCtrl_T0_period_in_10ns		= settingIOCtrlT0PeriodIn10nsDefault,
};
