#include "globals.h"
#include "enum.h"
#include "default_settings.h"

uint32_t tmp_aPIXEL[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint32_t* aPIXEL = tmp_aPIXEL;
uint32_t tmp_aCAMCNT[MAXPCIECARDS] = { 1, 1, 1, 1, 1 };	// cameras parallel
uint32_t* aCAMCNT = tmp_aCAMCNT;	// cameras parallel
bool useSWTrig_temp = false;
bool* useSWTrig = &useSWTrig_temp;
uint16_t* temp_userBuffer[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBuffer= temp_userBuffer;
uint16_t* temp_userBufferWritePos[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBufferWritePos = temp_userBufferWritePos;
uint32_t BOARD_SEL = 1;
uint32_t numberOfInterrupts = 0;
uint8_t number_of_boards = 0;
uint32_t Nob = 1;
uint32_t tmp_Nosbp = 1000;
uint32_t* Nospb = &tmp_Nosbp;
bool abortMeasurementFlag = false;
bool continiousMeasurementFlag = false;
uint32_t continiousPause = 0;
struct global_settings settings_struct =
{
    .nos                    = settingNosDefault,
    .nob                    = settingNobDefault,
    .sti_mode               = settingStiDefault,
    .bti_mode               = settingBtiDefault,
    .stime_in_microsec      = settingStime_in_microseconds_Default,
    .btime_in_microsec      = settingBtime_in_microseconds_Default,
    .sdat_in_10ns           = settingSdat_in_10nsDefault,
    .bdat_in_10ns           = settingSdat_in_10nsDefault,
    .sslope                 = settingSslopeDefault,
    .bslope                 = settingBslopeDefault,
    .xckdelay_in_10ns       = settingXckdelayIn10nsDefault,
    .ShutterExpTimeIn10ns   = settingShutterExpTimeIn10nsDefault,
    .trigger_mode_cc        = settingTriggerCcDefault,
    .board_sel              = settingBoardSelDefault,
    .sensor_type            = settingSensorTypeDefault,
    .camera_system          = settingCameraSystemDefault,
    .camcnt                 = settingCamcntDefault,
    .pixel                  = settingPixelDefault,
    .mshut                  = settingMshutDefault,
    .led_off                = settingLedDefault,
    .gain_switch            = settingGain3010Default,
    .gain_3030              = settingGain3030Default,
    .Temp_level             = settingCoolingDefault,
    .dac                    = settingDacDefault,
    .enable_gpx             = settingGpxDefault,
    .gpx_offset             = settingGpxOffsetDefault,
    .FFTLines               = settingLinesDefault,
    .Vfreq                  = settingVfreqDefault,
    .FFTMode                = settingFftModeDefault,
    .lines_binning          = settingLinesBinningDefault,
    .number_of_regions      = settingNumberOfRegionsDefault,
    .keep_first             = settingKeepFirstDefault,
    .region_size[0]         = settingRegionSize1Default,
    .region_size[1]         = settingRegionSize2Default,
    .region_size[2]         = settingRegionSize3Default,
    .region_size[3]         = settingRegionSize4Default,
    .region_size[4]         = settingRegionSize5Default,
    .region_size[5]         = settingRegionSize6Default,
    .region_size[6]         = settingRegionSize7Default,
    .region_size[7]         = settingRegionSize8Default,
    .dac_output[0]          = settingSensorOffsetChannel1Default,
    .dac_output[1]          = settingSensorOffsetChannel2Default,
    .dac_output[2]          = settingSensorOffsetChannel3Default,
    .dac_output[3]          = settingSensorOffsetChannel4Default,
    .dac_output[4]          = settingSensorOffsetChannel5Default,
    .dac_output[5]          = settingSensorOffsetChannel6Default,
    .dac_output[6]          = settingSensorOffsetChannel7Default,
    .dac_output[7]          = settingSensorOffsetChannel8Default,
    .TORmodus               = settingTorDefault,
    .ADC_Mode               = settingAdcModeDefault,
    .ADC_custom_pattern     = settingAdcCustomValueDefault,
    .bec_in_10ns            = settingBecIn10nsDefault
};
