#include "globals.h"
#include "default_settings.h"

uint32_t tmp_aPIXEL[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint32_t* aPIXEL = tmp_aPIXEL;
uint32_t tmp_aCAMCNT[MAXPCIECARDS] = { 1, 1, 1, 1, 1 };
uint32_t* aCAMCNT = tmp_aCAMCNT;
bool useSWTrig_temp = false;
bool* useSWTrig = &useSWTrig_temp;
uint16_t* temp_userBuffer[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBuffer= temp_userBuffer;
uint16_t* temp_userBufferEndPtr[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBufferEndPtr = temp_userBufferEndPtr;
volatile uint16_t* temp_userBufferWritePos[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
volatile uint16_t** userBufferWritePos = temp_userBufferWritePos;
uint16_t* temp_userBufferWritePos_last[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
uint16_t** userBufferWritePos_last = temp_userBufferWritePos_last;
volatile bool temp_timerOn[MAXPCIECARDS] = { false, false, false, false, false };
volatile bool* timerOn = temp_timerOn;
uint32_t temp_numberOfInterrupts[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
volatile uint32_t* numberOfInterrupts = temp_numberOfInterrupts;
uint8_t number_of_boards = 0;
uint32_t tmp_Nob = 1;
uint32_t* Nob = &tmp_Nob;
uint32_t tmp_Nosbp = 1000;
uint32_t* Nospb = &tmp_Nosbp;
bool abortMeasurementFlag = false;
volatile bool continiousMeasurementFlag = false;
uint32_t continiousPauseInMicroseconds = 0;
bool isRunning = false;
int64_t temp_scanCounterTotal[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
int64_t* scanCounterTotal = temp_scanCounterTotal;
uint64_t measurement_cnt = 0;
char start_timestamp[file_timestamp_size];
size_t temp_data_available[MAXPCIECARDS] = { 0, 0, 0, 0, 0 };
volatile size_t* data_available = temp_data_available;
volatile bool tmp_allInterruptsDone[MAXPCIECARDS] = { true, true, true, true, true };
volatile bool* allInterruptsDone = tmp_allInterruptsDone;
const struct camera_settings camera_settings_default =
{
	.use_software_polling = settingsUseSoftwarePollingDefault,
	.sti_mode = settingStiDefault,
	.bti_mode = settingBtiDefault,
	.stime_in_microsec = settingStime_in_microseconds_Default,
	.btime_in_microsec = settingBtime_in_microseconds_Default,
	.sdat_in_10ns = settingSdat_in_10nsDefault,
	.bdat_in_10ns = settingSdat_in_10nsDefault,
	.sslope = settingSslopeDefault,
	.bslope = settingBslopeDefault,
	.xckdelay_in_10ns = settingXckdelayIn10nsDefault,
	.sec_in_10ns = settingShutterSecIn10nsDefault,
	.trigger_mode_cc = settingTriggerCcDefault,
	.sensor_type = settingSensorTypeDefault,
	.camera_system = settingCameraSystemDefault,
	.camcnt = settingCamcntDefault,
	.pixel = settingPixelDefault,
	.led_off = settingLedDefault,
	.sensor_gain = settingSensorGainDefault,
	.adc_gain = settingAdcGainDefault,
	.temp_level = settingCoolingDefault,
	.gpx_offset = settingGpxOffsetDefault,
	.fft_lines = settingLinesDefault,
	.vfreq = settingVfreqDefault,
	.fft_mode = settingFftModeDefault,
	.lines_binning = settingLinesBinningDefault,
	.number_of_regions = settingNumberOfRegionsDefault,
	.keep = settingKeepDefault,
	.region_size[0] = settingRegionSize1Default,
	.region_size[1] = settingRegionSize2Default,
	.region_size[2] = settingRegionSize3Default,
	.region_size[3] = settingRegionSize4Default,
	.region_size[4] = settingRegionSize5Default,
	.region_size[5] = settingRegionSize6Default,
	.region_size[6] = settingRegionSize7Default,
	.region_size[7] = settingRegionSize8Default,
	.dac_output[0][0] = settingDacCameraDefault,
	.dac_output[0][1] = settingDacCameraDefault,
	.dac_output[0][2] = settingDacCameraDefault,
	.dac_output[0][3] = settingDacCameraDefault,
	.dac_output[0][4] = settingDacCameraDefault,
	.dac_output[0][5] = settingDacCameraDefault,
	.dac_output[0][6] = settingDacCameraDefault,
	.dac_output[0][7] = settingDacCameraDefault,
	.dac_output[1][0] = settingDacCameraDefault,
	.dac_output[1][1] = settingDacCameraDefault,
	.dac_output[1][2] = settingDacCameraDefault,
	.dac_output[1][3] = settingDacCameraDefault,
	.dac_output[1][4] = settingDacCameraDefault,
	.dac_output[1][5] = settingDacCameraDefault,
	.dac_output[1][6] = settingDacCameraDefault,
	.dac_output[1][7] = settingDacCameraDefault,
	.dac_output[2][0] = settingDacCameraDefault,
	.dac_output[2][1] = settingDacCameraDefault,
	.dac_output[2][2] = settingDacCameraDefault,
	.dac_output[2][3] = settingDacCameraDefault,
	.dac_output[2][4] = settingDacCameraDefault,
	.dac_output[2][5] = settingDacCameraDefault,
	.dac_output[2][6] = settingDacCameraDefault,
	.dac_output[2][7] = settingDacCameraDefault,
	.dac_output[3][0] = settingDacCameraDefault,
	.dac_output[3][1] = settingDacCameraDefault,
	.dac_output[3][2] = settingDacCameraDefault,
	.dac_output[3][3] = settingDacCameraDefault,
	.dac_output[3][4] = settingDacCameraDefault,
	.dac_output[3][5] = settingDacCameraDefault,
	.dac_output[3][6] = settingDacCameraDefault,
	.dac_output[3][7] = settingDacCameraDefault,
	.dac_output[4][0] = settingDacCameraDefault,
	.dac_output[4][1] = settingDacCameraDefault,
	.dac_output[4][2] = settingDacCameraDefault,
	.dac_output[4][3] = settingDacCameraDefault,
	.dac_output[4][4] = settingDacCameraDefault,
	.dac_output[4][5] = settingDacCameraDefault,
	.dac_output[4][6] = settingDacCameraDefault,
	.dac_output[4][7] = settingDacCameraDefault,
	.dac_output[5][0] = settingDacCameraDefault,
	.dac_output[5][1] = settingDacCameraDefault,
	.dac_output[5][2] = settingDacCameraDefault,
	.dac_output[5][3] = settingDacCameraDefault,
	.dac_output[5][4] = settingDacCameraDefault,
	.dac_output[5][5] = settingDacCameraDefault,
	.dac_output[5][6] = settingDacCameraDefault,
	.dac_output[5][7] = settingDacCameraDefault,
	.dac_output[6][0] = settingDacCameraDefault,
	.dac_output[6][1] = settingDacCameraDefault,
	.dac_output[6][2] = settingDacCameraDefault,
	.dac_output[6][3] = settingDacCameraDefault,
	.dac_output[6][4] = settingDacCameraDefault,
	.dac_output[6][5] = settingDacCameraDefault,
	.dac_output[6][6] = settingDacCameraDefault,
	.dac_output[6][7] = settingDacCameraDefault,
	.dac_output[7][0] = settingDacCameraDefault,
	.dac_output[7][1] = settingDacCameraDefault,
	.dac_output[7][2] = settingDacCameraDefault,
	.dac_output[7][3] = settingDacCameraDefault,
	.dac_output[7][4] = settingDacCameraDefault,
	.dac_output[7][5] = settingDacCameraDefault,
	.dac_output[7][6] = settingDacCameraDefault,
	.dac_output[7][7] = settingDacCameraDefault,
	.tor = settingTorDefault,
	.adc_mode = settingAdcModeDefault,
	.adc_custom_pattern = settingAdcCustomValueDefault,
	.bec_in_10ns = settingBecIn10nsDefault,
	.ioctrl_impact_start_pixel = settingIOCtrlImpactStartPixelDefault,
	.ioctrl_output_width_in_5ns[0] = settingIOCtrlOutput1WidthIn5nsDefault,
	.ioctrl_output_width_in_5ns[1] = settingIOCtrlOutput2WidthIn5nsDefault,
	.ioctrl_output_width_in_5ns[2] = settingIOCtrlOutput3WidthIn5nsDefault,
	.ioctrl_output_width_in_5ns[3] = settingIOCtrlOutput4WidthIn5nsDefault,
	.ioctrl_output_width_in_5ns[4] = settingIOCtrlOutput5WidthIn5nsDefault,
	.ioctrl_output_width_in_5ns[5] = settingIOCtrlOutput6WidthIn5nsDefault,
	.ioctrl_output_width_in_5ns[6] = settingIOCtrlOutput7WidthIn5nsDefault,
	.ioctrl_output_delay_in_5ns[0] = settingIOCtrlOutput1DelayIn5nsDefault,
	.ioctrl_output_delay_in_5ns[1] = settingIOCtrlOutput2DelayIn5nsDefault,
	.ioctrl_output_delay_in_5ns[2] = settingIOCtrlOutput3DelayIn5nsDefault,
	.ioctrl_output_delay_in_5ns[3] = settingIOCtrlOutput4DelayIn5nsDefault,
	.ioctrl_output_delay_in_5ns[4] = settingIOCtrlOutput5DelayIn5nsDefault,
	.ioctrl_output_delay_in_5ns[5] = settingIOCtrlOutput6DelayIn5nsDefault,
	.ioctrl_output_delay_in_5ns[6] = settingIOCtrlOutput7DelayIn5nsDefault,
	.ioctrl_T0_period_in_10ns = settingIOCtrlT0PeriodIn10nsDefault,
	.dma_buffer_size_in_scans = settingDmaBufferSizeInScansDefault,
	.tocnt = settingTocntDefault,
	.ticnt = settingTicntDefault,
	.sensor_reset_length_in_8_ns = settingSensorResetLengthIn8nsDefault,
	.write_to_disc = settingWriteToDiscDefault,
	.file_path = settingFilePathDefault,
	.file_split_mode = settingFileSplitModeDefault,
	.is_cooled_cam = settingIsCooledCamDefault
};

struct measurement_settings settings_struct =
{
	.board_sel						= settingBoardSelDefault,
	.nos							= settingNosDefault,
	.nob							= settingNobDefault,
	.contiuous_measurement			= settingContinuousMeasurementDefault,
	.cont_pause_in_microseconds		= settingContinuousPausInMicrosecondsDefault,
};
