#ifndef _LSCPCIEJ_LIB_H_
#define _LSCPCIEJ_LIB_H_

/************************************************************************
*  File: lscpciej_lib.h
*
*  Library for accessing PCI devices, possibly using a Kernel PlugIn driver.
*  The code accesses hardware using WinDriver's WDC library.
*  Code was generated by DriverWizard v14.0.0
*
*  Jungo Connectivity Confidential. Copyright (c) 2019 Jungo Connectivity Ltd.  https://www.jungo.com
*************************************************************************/
#include <stdio.h>
#include <stdarg.h>
#include "Jungo/wdc_defs.h"
#include "Jungo/utils.h"
#include "Jungo/status_strings.h"
#include "Jungo/pci_regs.h"
#include "Jungo/wdc_lib.h"
#include "Jungo/bits.h"

#ifdef __cplusplus
extern "C" {
#endif


/*************************************************************
  General definitions
 *************************************************************/
/* Kernel PlugIn driver name (should be no more than 8 characters) */
#define KP_LSCPCIEJ_DRIVER_NAME "KP_LSCPCIEJ"


/* Default vendor and device IDs (0 == all) */
/* TODO: Replace the ID values with your device's vendor and device IDs */
#define LSCPCIEJ_DEFAULT_VENDOR_ID 0x10EE /* Vendor ID */
#define LSCPCIEJ_DEFAULT_DEVICE_ID 0x7 /* Device ID */


/* Address space information struct */
#define MAX_TYPE 8
typedef struct {
    DWORD dwAddrSpace;
    CHAR sType[MAX_TYPE];
    CHAR sName[MAX_NAME];
    CHAR sDesc[MAX_DESC];
} LSCPCIEJ_ADDR_SPACE_INFO;

/* Interrupt result information struct */
typedef struct {
    DWORD dwCounter; /* Number of interrupts received */
    DWORD dwLost;    /* Number of interrupts not yet handled */
    WD_INTERRUPT_WAIT_RESULT waitResult; /* See WD_INTERRUPT_WAIT_RESULT values
                                            in windrvr.h */
    DWORD dwEnabledIntType; /* Interrupt type that was actually enabled
                               (MSI/MSI-X / Level Sensitive / Edge-Triggered) */
    DWORD dwLastMessage; /* Message data of the last received MSI/MSI-X
                            (Windows Vista and higher); N/A to line-based
                            interrupts. */
} LSCPCIEJ_INT_RESULT;
/* TODO: You can add fields to LSCPCIEJ_INT_RESULT to store any additional
         information that you wish to pass to your diagnostics interrupt
         handler routine (DiagIntHandler() in lscpciej_diag.c). */

/* LSCPCIEJ diagnostics interrupt handler function type */
typedef void (*LSCPCIEJ_INT_HANDLER)(WDC_DEVICE_HANDLE hDev,
    LSCPCIEJ_INT_RESULT *pIntResult);

/* LSCPCIEJ diagnostics plug-and-play and power management events handler function
 * type */
typedef void (*LSCPCIEJ_EVENT_HANDLER)(WDC_DEVICE_HANDLE hDev, DWORD dwAction);


/*************************************************************
  Internal definitions
 *************************************************************/
 /* WinDriver license registration string */
 /* TODO: When using a registered WinDriver version, replace the license string
		  below with your specific WinDriver license registration string and
		  replace the driver name below with your driver's name. */
#define LSCPCIEJ_DEFAULT_LICENSE_STRING "872759e7d022a2499e5dcb42c25d1f889fdfac803544b6979f345330df98.WD1400_64_NL_Entwicklungsbuero_Stresing"
#define LSCPCIEJ_DEFAULT_DRIVER_NAME WD_DEFAULT_DRIVER_NAME_BASE

		  /* PCI device information struct */
typedef struct {

	LSCPCIEJ_INT_HANDLER   funcDiagIntHandler;   /* Interrupt handler routine */
	LSCPCIEJ_EVENT_HANDLER funcDiagEventHandler; /* Event handler routine */

} LSCPCIEJ_DEV_CTX, *PLSCPCIEJ_DEV_CTX;
/* TODO: You can add fields to store additional device-specific information. */

/*************************************************************
  Global variables definitions
 *************************************************************/
 /* Last error information string */
static CHAR gsLSCPCIEJ_LastErr[256];

/* Library initialization reference count */
static DWORD LibInit_count = 0;

/*************************************************************
  Static functions prototypes and inline implementation
 *************************************************************/

#ifndef __KERNEL__
static BOOL DeviceValidate( const PWDC_DEVICE pDev );
static void LSCPCIEJ_EventHandler( WD_EVENT *pEvent, PVOID pData );
#endif
static void DLLCALLCONV LSCPCIEJ_IntHandler( PVOID pData );
void ErrLog( const CHAR *sFormat, ... );
static void TraceLog( const CHAR *sFormat, ... );

/*************************************************************
  Function prototypes
 *************************************************************/
/* -----------------------------------------------
    LSCPCIEJ and WDC libraries initialize/uninitialize
   ----------------------------------------------- */
/* Initialize the LSCPCIEJ and WDC libraries */
DWORD LSCPCIEJ_LibInit(void);
/* Uninitialize the LSCPCIEJ and WDC libraries */
DWORD LSCPCIEJ_LibUninit(void);

#ifndef __KERNEL__
/* -----------------------------------------------
    Device open/close
   ----------------------------------------------- */
/* Open a device handle */
WDC_DEVICE_HANDLE LSCPCIEJ_DeviceOpen(const WD_PCI_CARD_INFO *pDeviceInfo);
/* Close a device handle */
BOOL LSCPCIEJ_DeviceClose(WDC_DEVICE_HANDLE hDev);

/* -----------------------------------------------
    Interrupts
   ----------------------------------------------- */
/* Enable interrupts */
DWORD LSCPCIEJ_IntEnable(WDC_DEVICE_HANDLE hDev, LSCPCIEJ_INT_HANDLER funcIntHandler);
/* Disable interrupts */
DWORD LSCPCIEJ_IntDisable(WDC_DEVICE_HANDLE hDev);
/* Check whether interrupts are enabled for the given device */
BOOL LSCPCIEJ_IntIsEnabled(WDC_DEVICE_HANDLE hDev);

/* -----------------------------------------------
    Plug-and-play and power management events
   ----------------------------------------------- */
/* Register a plug-and-play or power management event */
DWORD LSCPCIEJ_EventRegister(WDC_DEVICE_HANDLE hDev,
    LSCPCIEJ_EVENT_HANDLER funcEventHandler);
/* Unregister a plug-and-play or power management event */
DWORD LSCPCIEJ_EventUnregister(WDC_DEVICE_HANDLE hDev);
/* Check whether a given plug-and-play or power management event is registered
 */
BOOL LSCPCIEJ_EventIsRegistered(WDC_DEVICE_HANDLE hDev);
#endif /* ifndef __KERNEL */

/* -----------------------------------------------
    Address spaces information
   ----------------------------------------------- */
/* Get number of address spaces */
DWORD LSCPCIEJ_GetNumAddrSpaces(WDC_DEVICE_HANDLE hDev);
/* Get address space information */
BOOL LSCPCIEJ_GetAddrSpaceInfo(WDC_DEVICE_HANDLE hDev,
    LSCPCIEJ_ADDR_SPACE_INFO *pAddrSpaceInfo);


/* -----------------------------------------------
    Debugging and error handling
   ----------------------------------------------- */
/* Get last error */
const char *LSCPCIEJ_GetLastErr(void);

#ifdef __cplusplus
}
#endif

#endif /* _LSCPCIEJ_LIB_H_ */

